version: '3.8'

services:
  web:
    container_name: django_dshum1
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python dshum1/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis

  redis:
    container_name: django_dshum1_redis
    image: redis:latest
    ports:
      - "6003:6379"
    restart: unless-stopped
    tty: true

  db:
    container_name: django_dshum1_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8103:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=karl
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=django_dshum1

volumes:
  postgres_data: