version: '3.8'

services:
  web:
    container_name: django_dshum1
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "while !</dev/tcp/db/${DB_INTERNAL_PORT:-5432}; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dshum1:/app
    ports:
      - "${WEB_EXTERNAL_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    tty: true

  redis:
    container_name: django_dshum1_redis
    image: redis:latest
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    restart: unless-stopped
    tty: true

  db:
    container_name: django_dshum1_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-django_dshum1}
    restart: unless-stopped
    tty: true

volumes:
  postgres_data: