# Generated by Django 4.1.7 on 2023-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linktag_alter_link_user_link_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktag',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
