# Generated by Django 4.1.7 on 2023-04-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_linktag_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='linktag',
            options={'ordering': ['title']},
        ),
    ]
