# Generated by Django 4.1.7 on 2023-03-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackMessage',
            new_name='Message',
        ),
    ]
