# Generated by Django 4.1.7 on 2023-03-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_token_options_alter_token_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='token',
            managers=[
            ],
        ),
    ]
